name: VPC resource provisioning workflow
on: workflow_dispatch

permissions:
    id-token: write
    contents: read

jobs:
    vpc_ci:
        name: "VPC Build"
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.7.3"


        - name: Install kubectl
          run: |
            curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
            
        - name: Terraform init
          working-directory: IAC/VPC-EKS
          run: terraform init
          continue-on-error: false

        - name: Terraform Format Check
          working-directory: IAC/VPC-EKS
          run: terraform fmt

        - name: Terraform Validate
          working-directory: IAC/VPC-EKS
          run: terraform validate
          continue-on-error: false

        - name: Terraform Plan
          working-directory: IAC/VPC-EKS
          run: terraform plan

        - name: Terraform Apply
          working-directory: IAC/VPC-EKS
          run: terraform apply -auto-approve


        
            
          
